apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 2204
          targetPort: 2204
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: kh-challenge_backend:latest
                  imagePullPolicy: Never # Pull local built image
                  envFrom:
                      - configMapRef:
                            name: backend-config
                  ports:
                      - containerPort: 2204
