apiVersion: v1
kind: Service
metadata:
    name: proxy-service
spec:
    type: NodePort
    selector:
        app: proxy
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: proxy
    template:
        metadata:
            labels:
                app: proxy
        spec:
            containers:
                - name: proxy
                  image: nginx:latest
                  volumeMounts:
                      - name: proxy-config-volume
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
                  ports:
                      - containerPort: 8080
            volumes:
                - name: proxy-config-volume
                  configMap:
                      name: proxy-config
