apiVersion: v1
kind: Service
metadata:
    name: pubsub-service
spec:
    selector:
        app: pubsub
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pubsub
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pubsub
    template:
        metadata:
            labels:
                app: pubsub
        spec:
            containers:
                - name: pubsub
                  image: redis:alpine
