version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: kuechenheld-frontend
    env_file:
      - .frontend.env
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    build: ./backend
    container_name: kuechenheld-backend
    env_file:
      - .backend.env
    depends_on:
      - database
      - pubsub
    networks:
      - frontend-network
      - backend-network

  database:
    image: mysql:8
    container_name: kuechenheld-database
    env_file:
      - .database.env
    volumes:
      - kuechenheld_data:/var/lib/mysql
    networks:
      - backend-network

  pubsub:
    image: redis:alpine
    container_name: kuechenheld-pubsub
    networks:
      - backend-network
  
  proxy:
    image: nginx:latest
    container_name: kuechenheld-proxy
    restart: unless-stopped
    ports: 
      - 8080:8080
    volumes:
      - .proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks: 
      - frontend-network

volumes:
  kuechenheld_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
